version: '3.9'
services:
  server:
    build: ./server
    env_file: ./server/.env.example
    volumes:
      - ./server:/app
      - ./server/data:/app/data
    ports:
      - "3001:3001"
    command: npm run start

  printer:
    build: ./printer-service
    working_dir: /app
    volumes:
      - ./printer-service:/app
    ports:
      - "4000:4000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_API_URL=http://server:3001
    ports:
      - "5173:5173"