version: '3.9'
services:
  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - ./server/data:/app/data
    depends_on:
      - printer
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
  printer:
    build: ./printer-service
    ports:
      - "4000:4000"

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: posq
      MYSQL_USER: posq
      MYSQL_PASSWORD: posq
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
