<<<<<<< HEAD
<<<<<<< HEAD
version: '3.8'

services:
  # Backend API Server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_TYPE=sqlite
      - DB_PATH=/app/data/posq.db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./server/data:/app/data
      - ./server/uploads:/app/uploads
    depends_on:
      - redis
    networks:
      - posq-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api
    networks:
      - posq-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - posq-network

  # Printer Service
  printer:
    build:
      context: ./printer-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - posq-network

  # MySQL for cloud mode (optional)
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=posq
      - MYSQL_USER=posq
      - MYSQL_PASSWORD=posqpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - posq-network
    profiles:
      - cloud

volumes:
  redis_data:
  mysql_data:

networks:
  posq-network:
    driver: bridge
=======
=======
>>>>>>> origin/main
version: '3.9'
services:
  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - ./server/data:/app/data
    depends_on:
      - printer
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
  printer:
    build: ./printer-service
    ports:
      - "4000:4000"

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: posq
      MYSQL_USER: posq
      MYSQL_PASSWORD: posq
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
<<<<<<< HEAD
>>>>>>> e0c392214cbb541e36508749d9336f9cc9e18c38
=======
>>>>>>> origin/main
