import { useEffect, useState } from 'react'
import { reservationsAPI } from '../../services/api'
const transitions = {pending:['confirmed','cancelled'],confirmed:['seated','cancelled','no_show'],seated:['completed']}
export default function ReservationsPage() {
 const [rows,setRows]=useState([]), [filter,setFilter]=useState('active'), [error,setError]=useState(''), [loading,setLoading]=useState(true), [busy,setBusy]=useState(null)
 const load=()=>reservationsAPI.list().then(({data})=>setRows(data.reservations)).catch(()=>setError('Could not load reservations')).finally(()=>setLoading(false))
 useEffect(()=>{load()},[])
 const update=async(id,status)=>{setBusy(id);setError('');try{await reservationsAPI.update(id,status);await load()}catch(e){setError(e.response?.data?.error||'Could not update reservation')}finally{setBusy(null)}}
 const filtered=rows.filter(r=>filter==='all'||['pending','confirmed','seated'].includes(r.status))
 return <div className="p-4 sm:p-8"><div className="flex flex-wrap justify-between gap-4 mb-8"><div><h1 className="text-3xl font-bold">Reservations</h1><p className="text-slate-500 mt-2">Welcome guests, assign their visit, and keep every table on schedule.</p></div><select aria-label="Filter reservations" className="flow-input w-auto" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active reservations</option><option value="all">All reservations</option></select></div>{error&&<p role="alert" className="text-red-700 mb-4">{error}</p>}{loading?<p>Loading reservations…</p>:!filtered.length?<div className="flow-panel text-center">No reservations here yet. Customers can reserve from your public website.</div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(r=><article className="flow-panel" key={r.id}><div className="flex justify-between gap-2"><h2 className="font-semibold text-lg">{r.customer_name}</h2><span className="text-xs uppercase rounded-full bg-stone-100 px-3 py-2">{r.status.replace('_',' ')}</span></div><p className="mt-4 font-medium">{new Date(r.start_time).toLocaleString()}</p><p className="text-slate-600 mt-2">{r.party_size} guests · Table {r.table_number} · 90 min</p><a className="block mt-2 underline" href={`tel:${r.customer_phone}`}>{r.customer_phone}</a>{r.notes&&<p className="text-sm text-slate-500 mt-3">{r.notes}</p>}<div className="flex flex-wrap gap-2 mt-5">{(transitions[r.status]||[]).map(status=><button key={status} disabled={busy===r.id} className="flow-choice capitalize" onClick={()=>update(r.id,status)}>{status.replace('_',' ')}</button>)}</div></article>)}</div>}</div>
}
